import type { Metadata } from 'next'
import './globals.css'
import Nav from './components/Nav'


export const metadata: Metadata = {
  title: 'Role Based Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-100'>
        <Nav />
        <div className="m-2">
          {children}
        </div>
      </body>
    </html>
  )
}
